version: '3.9'
#deploy with: docker compose up -d
services:
  app-be:
    image: 'vaslim/subtitlefts'
    build:
      dockerfile: Dockerfile
    network_mode: host
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE} #active profile, one of: local, dev, prod
      - JOB_CRON=${JOB_CRON} #cron schedule for automatic run
      - ELASTICSEARCH_ADDRESS=${ELASTICSEARCH_ADDRESS}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - FILES_ITERATION_SIZE=${FILES_ITERATION_SIZE} #number of files to index at once, lower values use less memory, higher values increase performance
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - JWT_SECRET=${JWT_SECRET} #change this
      - CATEGORY_INFO_INDEX_FILE_EXTENSION=${CATEGORY_INFO_INDEX_FILE_EXTENSION} #file extension used to index videos for information, can be .mp4, .vtt or something else if needed, parses path for info
    restart: always
    #depends_on:
      #elasticsearch:
        #condition: service_healthy
    volumes:
      - ${DATA_BASE_PATH}:/mnt/data #data volume with subtitles
      - certs:/usr/share/ssl_bundle
  create_certs:
    container_name: create_certs
    image: elasticsearch:8.11.3
    command: >
      bash -c '
        if [[ ! -f ./config/certificates/elastic-certificates.p12 ]]; then
          bin/elasticsearch-certutil cert -out config/certificates/elastic-certificates.p12 -pass ""
        fi;
        chown -R 1000:0 /usr/share/elasticsearch/config/certificates
      '
    user: "0"
    working_dir: /usr/share/elasticsearch
    volumes: ['certs:/usr/share/elasticsearch/config/certificates']

  elasticsearch:
    image: elasticsearch:8.11.3
    container_name: elasticsearch01
    network_mode: host
    restart: always
    deploy:
      resources:
        limits:
          memory: 5G
    #healthcheck:
    #  test: [ "CMD", "curl", "-f", "http://localhost:9200" ]
    #  interval: 30s
    #  timeout: 10s
    #  retries: 5

    environment:
    - discovery.type=single-node
    - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}
    - xpack.security.enabled=true
    - xpack.security.transport.ssl.enabled=false
    #- xpack.security.transport.ssl.verification_mode=certificate
    #- xpack.security.transport.ssl.keystore.path=/usr/share/elasticsearch/config/certificates/elastic-certificates.p12
    #- xpack.security.transport.ssl.truststore.path=/usr/share/elasticsearch/config/certificates/elastic-certificates.p12
    volumes: ['esdata:/usr/share/elasticsearch/data', 'certs:/usr/share/elasticsearch/config/certificates']


volumes: {"esdata", "certs"}