version: '3.9'
#deploy with: docker compose up -d
services:
  app-be:
    image: 'vaslim/subtitlefts'
    build:
      dockerfile: Dockerfile
    ports:
      - "8083:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev #active profile, one of: local, dev, prod
      - JOB_CRON=0 0 14 * * ? #cron schedule for automatic run
      - ELASTICSEARCH_ADDRESS=elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=8H5pCjTxZdvX=+1_qfG5
      - FILES_ITERATION_SIZE=10 #number of files to index at once, lower values use less memory, higher values increase performance
      - ADMIN_PASSWORD=mysecurepassword
      - JWT_SECRET=r2Jwsg7xCKvHh2feB2FGsCr2Jwsg7xCKvHh2feB2FGsC #change this

    depends_on:
      - elasticsearch
    volumes:
      - /var/home/vaslim/Videos/batchtool2:/mnt/data #data volume with subtitles
      - certs:/usr/share/ssl_bundle
  create_certs:
    container_name: create_certs
    image: elasticsearch/elasticsearch:8.9.2
    command: >
      bash -c '
        if [[ ! -f ./config/certificates/elastic-certificates.p12 ]]; then
          bin/elasticsearch-certutil cert -out config/certificates/elastic-certificates.p12 -pass ""
        fi;
        chown -R 1000:0 /usr/share/elasticsearch/config/certificates
      '
    user: "0"
    working_dir: /usr/share/elasticsearch
    volumes: ['certs:/usr/share/elasticsearch/config/certificates']

  elasticsearch:
    image: elasticsearch/elasticsearch:8.9.2
    container_name: elasticsearch01
    networks:
      - elastic
    ports:
    - "9200:9200"
    deploy:
      resources:
        limits:
          memory: 3G
    environment:
    - discovery.type=single-node
    - ELASTIC_PASSWORD=8H5pCjTxZdvX=+1_qfG5
    - xpack.security.enabled=true
    - xpack.security.transport.ssl.enabled=true
    - xpack.security.transport.ssl.verification_mode=certificate
    - xpack.security.transport.ssl.keystore.path=/usr/share/elasticsearch/config/certificates/elastic-certificates.p12
    - xpack.security.transport.ssl.truststore.path=/usr/share/elasticsearch/config/certificates/elastic-certificates.p12
    volumes: ['esdata:/usr/share/elasticsearch/data', 'certs:/usr/share/elasticsearch/config/certificates']

networks:
  elastic:

volumes: {"esdata", "certs"}